Add opentelemetry as tracing provider
virtual-kubelet/virtual-kubelet pull request #1006
Opened 2022-07-04 10:33 UTC by yabuchan

**What type of PR is this?**
/feature

**What this PR does / why we need it:**
Fixes #1005

**Special notes for your reviewer:**
* Currently opentelemetry hasn't supported log signal in span, so left TODO comment as saving log in span.
* Latest opentelemetry (v1.7.0) requires go-logr/logr v1.2 which conflicts with k8s.io/apimachinery. Safe to bump up to opentelemetry (v1.7.0) by removing `replace` lines in go.mod file once k8s.io/apimachinery is updated. 

**How was it tested:**
`make test` is passed

2022-07-05 16:25 UTC, cpuguy83 requested changes

2022-07-05 16:25 UTC, cpuguy83 commented on trace/opentelemetry/opentelemetry.go
> +package openTelemetry
```suggestion
package opentelemetry
```

2022-07-05 16:25 UTC, cpuguy83 commented on trace/opentelemetry/opentelemetry.go
> +	//TODO Add log event to span once it is available.
This would be `span.AddEvent`

2022-07-05 16:25 UTC, cpuguy83 commented on trace/opentelemetry/opentelemetry.go
> +	//TODO Add log event to span once it is available.
Or at least that is how I've done this in other projects.

2022-07-07 15:21 UTC, yabuchan commented on trace/opentelemetry/opentelemetry.go
> +package openTelemetry
good catch. Updated.

2022-07-07 17:07 UTC, cpuguy83 commented
```
trace/opentelemetry/opentelemetry.go:15:1: commentFormatting: put a space between `//` and comment text (gocritic)
// Package openTelemetry implements a github.com/virtual-kubelet/virtual-kubelet/trace.Tracer
^
trace/opentelemetry/opentelemetry_test.go:45:3: ineffectual assignment to `ctx` (ineffassign)
		ctx, s := a.StartSpan(ctx, "name")
		^
trace/opentelemetry/opentelemetry_test.go:185:4: ineffectual assignment to `ctx` (ineffassign)
			ctx = s.WithFields(ctx, tt.fields)
			^
trace/opentelemetry/opentelemetry_test.go:257:4: ineffectual assignment to `ctx` (ineffassign)
			ctx, s := otel.Tracer(tt.spanName).Start(ctx, tt.spanName)
			^
trace/opentelemetry/opentelemetry.go:51:19: func `logLevel.string` is unused (unused)
```

2022-08-31 05:47 UTC, cpuguy83 commented
This is great.
I've been holding off merging due to CI issues.
I have a pr open to address that.

Could you have the cli use this instead of opencensus? I think we can just add in otlp support in the cli and drop all the opencensus stuff.

2022-08-31 18:29 UTC, merged