ci: Migrate lint/test to Github actions
virtual-kubelet/virtual-kubelet pull request #1007
Opened 2022-07-13 17:37 UTC by helayoty

2022-07-13 21:44 UTC, cpuguy83 requested changes

2022-07-13 21:44 UTC, cpuguy83 commented on Makefile
> +GOLANGCI_LINT_VER := v1.41.1
Can we use this action instead of dealing with installing the bin here? https://github.com/golangci/golangci-lint-action

2022-07-13 21:44 UTC, cpuguy83 commented on Makefile
> +	$(GOIMPORTS) -local go.goms.io/fleet -w $$(go list -f {{.Dir}} ./...)
What's this `-local` for?

2022-07-13 21:47 UTC, cpuguy83 requested changes

2022-07-13 21:47 UTC, cpuguy83 commented on .github/workflows/lint.yml
> +  GO_VERSION: '1.15'
We should use the latest go for linting, I think.

2022-07-13 21:47 UTC, cpuguy83 commented on .github/workflows/tests.yml
> +          go-version: ${{ secrets.GO_VERSION  }}
Secret?

2022-07-13 21:47 UTC, cpuguy83 commented on .github/workflows/tests.yml
> +          go-version: ${{ secrets.GO_VERSION  }}
Also thinking this might be nice to do with a matrix of go versions.

2022-07-13 22:33 UTC, helayoty commented on Makefile
> +	$(GOIMPORTS) -local go.goms.io/fleet -w $$(go list -f {{.Dir}} ./...)
wrong typing, removed.

2022-08-31 18:05 UTC, cpuguy83 commented
Closing this since #1015 super-ceded this.

2022-08-31 18:05 UTC, closed without merging