add attach API functionality
virtual-kubelet/virtual-kubelet pull request #1090
Opened 2023-03-16 18:59 UTC by aka-somix

Extended virtual kubelet API with the "Attach" subresource.

Added

    Attach funtionality to remote commands
    Attach functionality API handler

Changed

    update PodHandlerConfig to also manage attach method
    update Provider interface to also have an AttachToContainer property

2023-03-17 11:59 UTC, aka-somix commented
/easycla

2023-03-28 14:22 UTC, aka-somix commented
Hi! 
Thank you. I have rebased my branch to align it with the master branch, but pushing it caused the Unit tests check to fail and it do not know if I can run again checks.
I saw that unit tests basically timed out, there is something we can do to run them again or you are going to do that for us?

2023-03-28 15:07 UTC, cpuguy83 requested changes

2023-03-28 15:07 UTC, cpuguy83 commented on node/api/attach.go
> +// HandleContainerExec makes an http handler func from a Provider which execs a command in a pod's container
doc string is for exec instead of attach

2023-03-28 15:07 UTC, cpuguy83 commented on node/nodeutil/provider.go
> +	AttachToContainer(ctx context.Context, namespace, podName, containerName string, attach api.AttachIO) error
Let's make sure to call this change out in the release notes

2023-03-31 15:51 UTC, merged

2023-03-31 19:04 UTC, pires commented on node/api/attach.go
> +// ContainerAttachHandlerFunc defines the handler function used for "execing" into a
The linter didn't complain (?) :(