interLink provider documentation
virtual-kubelet/virtual-kubelet pull request #1214
Opened 2024-05-02 06:06 UTC by dciangot

Hi, this is to propose to include [interLink](https://intertwin-eu.github.io/interLink/) in the list of providers.
We presented it at the last [CNCF AI Day in Paris](https://colocatedeventseu2024.sched.com/event/1YFfQ/pods-everywhere-interlink-a-virtual-kubelet-abstraction-streamlining-hpc-resource-exploitation-diego-ciangottini-infn) and then in the [Research end user group](https://youtu.be/7MTb8iyvG5Q?si=MjB_FKtCUAJl-_aj), where I got the suggestion to show it as a provider here, although it is a project at early development stage.

For context, as mentioned in the content of the PR: "InterLink is a Virtual Kubelet provider that can manage container lifecycle through a well defined API specification, allowing for any resource provider to be integrated with a simple http server and a handful of methods.
In other words, this is an attempt to streamline the process of creating custom Virtual Kubelet providers, avoiding the need for any resource provider to implement its own version of a Kubelet workflow, which would require having some domain expertise in the Kubernetes internals."

2024-05-07 20:52 UTC, helayoty commented on README.md
> +For detailed instruction, follow the guide [here](phttps://intertwin-eu.github.io/interLink/docs/category/guides).
This link does not work.

2024-05-07 20:53 UTC, helayoty requested changes
Can you please fix the guide link?

2024-05-07 21:00 UTC, dciangot commented
Done, sorry about that!

2024-05-10 21:16 UTC, helayoty approved these changes
LGTM 🚢

2024-05-10 21:29 UTC, merged