Add CodeQL Security Scanning
virtual-kubelet/virtual-kubelet pull request #922
Opened 2020-12-02 18:38 UTC by caniszczyk

Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>

2020-12-03 19:39 UTC, sargun requested changes
I'm not totally sure what CodeQL does, and where the results of these actions go. Can you add a little bit to your commit comment about that?

2020-12-03 19:39 UTC, sargun commented on .github/workflows/codeql-analysis.yml
> +        language: [ 'go', 'javascript' ]
Can you remove javascript?

2020-12-03 19:39 UTC, sargun commented on .github/workflows/codeql-analysis.yml
> +# For most projects, this workflow file will not need changing; you simply need
I think you can remove this note.

2020-12-14 16:58 UTC, sargun commented
@caniszczyk Ping?

2020-12-14 20:29 UTC, caniszczyk commented on .github/workflows/codeql-analysis.yml
> +# For most projects, this workflow file will not need changing; you simply need
removed the note

2020-12-14 20:29 UTC, caniszczyk commented on .github/workflows/codeql-analysis.yml
> +        language: [ 'go', 'javascript' ]
done

2020-12-15 04:13 UTC, merged